### ISSUE TITLE
rv64g_instr_fetch

### ISSUE THREAD

**Issue by SubhanBihan** [DSi-DV/maverickOne#49]
Joint development

**Comment by foez-ahmed** [comment]
It seems that we need one more pin called `fetch_enable_i`
When this pin is set low, **output valid/ready/req/gnt goes low**. The device sits seemingly idle

**Comment by foez-ahmed** [comment]
`is_jump == 1` & `dna_load == 0` is not illegal. It's complicated, need a bit brainstorming

**Comment by foez-ahmed** [comment]
dismissed by https://github.com/DSi-DV/maverickOne/issues/72
