### ISSUE TITLE
regfile performance improvement

### ISSUE THREAD

**Issue by foez-ahmed** [DSi-DV/maverickOne#56]
Add forward paths for data and locks

**Comment by foez-ahmed** [comment]
@tahmeedKENJI I'll let you know when to begin once the design changes are there

**Comment by foez-ahmed** [comment]
@tahmeedKENJI RTL is ready

**Comment by foez-ahmed** [comment]
Suppose `rs1_addr` is `20` currently locked. But we have Unlock arriving for it in the same cycle. So instead of waiting for the unlocking, we're rerouting the `rs1_data` from `unlock_data`

I don't remember the exact pin names, but you'll be able to relate to correct name

**Comment by foez-ahmed** [comment]
@tahmeedKENJI are you working on this?

**Comment by tahmeedKENJI** [comment]
Yes vaiya. I'll send in the PR as soon as I'm done.

**Comment by foez-ahmed** [comment]
0f931e4bd02e6cd693fd0da8f82a3225a4dc691e
